### ISSUE TITLE
Increase minimum widget sizes for CJK

### ISSUE THREAD

**Issue by AaronVanGeffen** [oli414/OliUI#8]
The OpenRCT2 sprite font is 10px high, which provides enough expressivity for languages using the Cyrillic, Greek, and Latin alphabets. However, East-Asian languages like Chinese, Japanese, and Korean require at least 12px high for their glyphs.

We have been changing OpenRCT2 to accommodate these by increasing widget sizes for buttons, spinners, and dropdowns. Typically, this results in a 2px increase in height for affected elements.

Currently, OliUI appears to use 13px as the default widget size for most widgets, e.g. buttons. I would like to request this be increased with CJK languages in mind as well.

**Comment by AaronVanGeffen** [comment]
Could you elaborate on closing this? To my knowledge, the issue hasn't been addressed. Is that correct?

**Comment by oli414** [comment]
Woops sorry, I thought this was handled by Sadret's PR
